
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: analytics
spec:
  ports:
  - port: 8123
    targetPort: 8123
    protocol: TCP
    name: http
  selector:
    app: clickhouse
