
apiVersion: v1
kind: Service
metadata:
  name: superset
  namespace: analytics
spec:
  ports:
  - port: 8088
    targetPort: 8088
    protocol: TCP
    name: http
  selector:
    app: superset
